version: '3'

services:
    python_app:
        image: python:3
        container_name: python_app
        stdin_open: true
        tty: true
        working_dir: /app
        command: /app/entrypoint.sh
        volumes:
            - "./:/app/"
