version: '3'

services:
    python_app:
        image: python3-dev-tests
        build: .
        container_name: python_app
        stdin_open: true
        tty: true
        working_dir: /app
        command: python3 main.py
        volumes:
            - "./:/app/"
